# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 00:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_radii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_ions',
            name='cn',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=20), default='', size=20),
            preserve_default=False,
        ),
    ]
