# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 02:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_radii', '0007_db_ions_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_ions',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=20), size=20),
        ),
    ]
