# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 01:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_radii', '0008_auto_20171208_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_ions',
            name='cn',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=20), size=20),
        ),
    ]
